version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nest_backend
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   container_name: nest_backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_DATABASE: ${DB_DATABASE}
  #     JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
  #     JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
  #     JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  #     JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
  #   depends_on:
  #     - db

volumes:
  postgres_data: